Dont create/update buildpack entry when uploading blobs fails
* We only run buildpack installer on the first worker of instance 0

[#69100160]

Signed-off-by: James Myers <jmyers@pivotallabs.com>

diff --git a/bosh-templates/cloud_controller_api_worker_ctl.erb b/bosh-templates/cloud_controller_api_worker_ctl.erb
--- a/bosh-templates/cloud_controller_api_worker_ctl.erb
+++ b/bosh-templates/cloud_controller_api_worker_ctl.erb
@@ -48,11 +48,13 @@ case $1 in
     
     # Run the buildpack install only on the first CC Worker launch
     <% if spec.index.to_i == 0 %>
-    chpst -u vcap:vcap bundle exec rake buildpacks:install
+    if [ $2 == 1 ]; then
+      chpst -u vcap:vcap bundle exec rake buildpacks:install
 
-    if [ $? != 0 ]; then
-      echo "Buildpacks installation failed"
-      exit 1
+      if [ $? != 0 ]; then
+        echo "Buildpacks installation failed"
+        exit 1
+      fi
     fi
     <% end %>
 
