check for nfs mount to exist before starting
[#98158086]

diff --git a/bosh-templates/cloud_controller_api_ctl.erb b/bosh-templates/cloud_controller_api_ctl.erb
--- a/bosh-templates/cloud_controller_api_ctl.erb
+++ b/bosh-templates/cloud_controller_api_ctl.erb
@@ -54,6 +54,25 @@ case $1 in
 
     pid_guard $PIDFILE "Cloud controller ng"
 
+    <% if properties.nfs_server.address %>
+    export NFS_SHARE=<%= p('nfs_server.share_path') %>
+
+    echo "Checking for nfs to be mounted"
+
+    nfs_check_attempts=0
+    while [[ ! -f $NFS_SHARE/shared/.nfs_test ]]; do
+      sleep 0.1
+      nfs_check_attempts=$((nfs_check_attempts+1))
+
+      if [[ $nfs_check_attempts -eq 300 ]]; then
+        echo "Failed to find nfs mount"
+        exit 1
+      fi
+    done
+
+    echo "nfs is mounted"
+    <% end %>
+
     <% if_p("cc.directories.diagnostics") do |diag_dir| %>
     mkdir -p <%= diag_dir %>
     chown vcap:vcap <%= diag_dir %>
