Ensure that drain scripts always print 0 for success
Before this, `kill_and_wait` would sometimes `exit 0` without printing
`0`. Bosh only considers the drain successful if it prints 0.

Also, cc-drain sometimes wouldn't print 0 because of the ruby print
buffer. We force the buffer to flush now.

[#151609175]

Signed-off-by: Eric Promislow <eric.promislow@suse.com>

diff --git a/bosh/jobs/cloud_controller_clock/templates/drain.sh.erb b/bosh/jobs/cloud_controller_clock/templates/drain.sh.erb
--- a/bosh/jobs/cloud_controller_clock/templates/drain.sh.erb
+++ b/bosh/jobs/cloud_controller_clock/templates/drain.sh.erb
@@ -7,13 +7,20 @@ exit 0
 <% else %>
 RUN_DIR="/var/vcap/sys/run/cloud_controller_clock"
 PIDFILE="${RUN_DIR}/cloud_controller_clock.pid"
+LOG_DIR="/var/vcap/sys/log/cloud_controller_clock/drain"
 
 source /var/vcap/packages/capi_utils/pid_utils.sh
+mkdir -p $LOG_DIR
 
 if [ -f "${PIDFILE}" ]; then
-  kill_and_wait "$PIDFILE" 30 &> /dev/null
+  if ! ( kill_and_wait "$PIDFILE" 30 &>> "$LOG_DIR/drain.log" ); then
+    exit $?
+  fi
+else
+  echo "$PIDFILE not found" &>> "$LOG_DIR/drain.log"
 fi
 
-echo 0 # tell bosh not wait for anything
-exit 0
+echo "killed the clock" &>> "$LOG_DIR/drain.log"
+
+echo 0 # tell bosh the drain script succeeded
 <% end %>
diff --git a/bosh/jobs/cloud_controller_ng/templates/drain.sh.erb b/bosh/jobs/cloud_controller_ng/templates/drain.sh.erb
--- a/bosh/jobs/cloud_controller_ng/templates/drain.sh.erb
+++ b/bosh/jobs/cloud_controller_ng/templates/drain.sh.erb
@@ -15,16 +15,24 @@ exit 0
 
 RUN_DIR="/var/vcap/sys/run/cloud_controller_ng"
 JOB_DIR="/var/vcap/jobs/cloud_controller_ng"
+LOG_DIR="/var/vcap/sys/log/cloud_controller_ng/drain"
 
 source /var/vcap/packages/capi_utils/pid_utils.sh
+mkdir -p $LOG_DIR
 
 for i in {1..<%=p("cc.jobs.local.number_of_workers")%>}; do
   pidfile="${RUN_DIR}/cloud_controller_worker_${i}.pid"
 
   if [ -f "${pidfile}" ]; then
-    kill_and_wait "$pidfile" 30 &> /dev/null
+    if !( kill_and_wait "$pidfile" 30 &>> "$LOG_DIR/drain_${i}.log" ); then
+      exit $?
+    fi
+  else
+    echo "$pidfile not found" &>> "$LOG_DIR/drain_${i}.log"
   fi
 done
+
+echo "killed all the workers" &>> "$LOG_DIR/drain_${i}.log"
 
 exec "${JOB_DIR}/bin/cc-drain"
 
diff --git a/bosh/jobs/cloud_controller_worker/templates/drain.sh.erb b/bosh/jobs/cloud_controller_worker/templates/drain.sh.erb
--- a/bosh/jobs/cloud_controller_worker/templates/drain.sh.erb
+++ b/bosh/jobs/cloud_controller_worker/templates/drain.sh.erb
@@ -12,17 +12,27 @@ exit 0
 <% else %>
 
 RUN_DIR="/var/vcap/sys/run/cloud_controller_worker"
+LOG_DIR="/var/vcap/sys/log/cloud_controller_worker/drain"
+
 source /var/vcap/packages/capi_utils/pid_utils.sh
+mkdir -p $LOG_DIR
+
 
 for i in {1..<%=p("cc.jobs.generic.number_of_workers")%>}; do
+
   pidfile="${RUN_DIR}/cloud_controller_worker_${i}.pid"
 
   if [ -f "${pidfile}" ]; then
-    kill_and_wait "$pidfile" 30 &> /dev/null
+    if ! ( kill_and_wait "$pidfile" 30 >> "$LOG_DIR/drain_${i}.log" ); then
+      exit $?
+    fi
+  else
+    echo "$pidfile not found" >> "$LOG_DIR/drain_${i}.log"
   fi
 done
 
-echo 0 # tell bosh not wait for anything
-exit 0
+echo "killed all the workers" >> "$LOG_DIR/drain_${i}.log"
+
+echo 0 # tell bosh the drain script succeeded
 
 <% end %>
